name: "linting"

on:
  workflow_call:

permissions:
  pull-requests: read

jobs:
  validate-pr-title:
    name: conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            fix
            feat
            chore
          ignoreLabels: |
            autorelease
            dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-tflint:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: v0.47.0

      - name: Run TFLint
        run: tflint --recursive

  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - name: terraform fmt
        run: terraform fmt -check -recursive
        continue-on-error: false

tests:
  name: tests
  runs-on: ubuntu-latest
  steps:
    - name: check out called repo
      uses: actions/checkout@v2
      with:
        repository: aztfmods/workflows-shared
        path: workflows-shared

    - name: setup go
      uses: actions/setup-go@v3
      with:
        check-latest: true

    - name: fetch go modules
      working-directory: workflows-shared/tests
      run: go mod download

    - name: check out caller repo
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        path: repo

    - name: run global tests
      working-directory: workflows-shared/tests
      run: go test -v ./...
      env:
        README_PATH: "${{ github.workspace }}/repo/README.md"
