name: "linting"

on:
  workflow_call:

permissions:
  pull-requests: read

jobs:
  validate-pr-title:
    name: conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            fix
            feat
            chore
          ignoreLabels: |
            autorelease
            dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-tflint:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        with:
          tflint_version: v0.47.0

      - name: Init TFLint
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}

      - uses: terraform-linters/tflint-load-config-action@v1
        with:
          source-repo: https://github.com/aztfmods/shared/workflows/.github/workflows

      - name: Run TFLint
        run: tflint --recursive

  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - name: terraform fmt
        run: terraform fmt -check -recursive
        continue-on-error: false

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: terraform fmt
        run: terraform fmt -check -recursive
        continue-on-error: false

